USE sala03v2_4;
SET SESSION sql_mode = REPLACE(REPLACE(@@sql_mode, 'NO_ZERO_DATE', ''), 'NO_ZERO_IN_DATE', '');

ALTER TABLE asignaciones_unidades_choferes MODIFY COLUMN fecha_fin datetime NULL DEFAULT NULL COMMENT 'Campo fecha_fin de la tabla asignaciones_unidades_choferes.';
ALTER TABLE asignaciones_unidades_choferes MODIFY COLUMN observaciones text NULL COMMENT 'Campo observaciones de la tabla asignaciones_unidades_choferes.';
ALTER TABLE asignaciones_unidades_choferes MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla asignaciones_unidades_choferes.';
ALTER TABLE asignaciones_unidades_choferes MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla asignaciones_unidades_choferes.';
ALTER TABLE asignaciones_unidades_choferes MODIFY COLUMN fecha_actualizacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo fecha_actualizacion de la tabla asignaciones_unidades_choferes.';
ALTER TABLE ayuda_social MODIFY COLUMN ticket_interno varchar(20) NULL DEFAULT NULL COMMENT 'Campo ticket_interno de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN id_usuario int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN id_tipo_ayuda_social int(11) NULL DEFAULT NULL COMMENT 'Campo id_tipo_ayuda_social de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN id_solicitud_ayuda_social int(11) NULL DEFAULT NULL COMMENT 'Campo id_solicitud_ayuda_social de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN id_estado_solicitud int(11) NULL DEFAULT NULL COMMENT 'Campo id_estado_solicitud de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN tipo_ayuda varchar(100) NULL DEFAULT NULL COMMENT 'Campo tipo_ayuda de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN fecha_ayuda date NULL DEFAULT NULL COMMENT 'Campo fecha_ayuda de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN descripcion text NULL COMMENT 'Campo descripcion de la tabla ayuda_social.';
ALTER TABLE ayuda_social MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla ayuda_social.';
ALTER TABLE beneficiarios MODIFY COLUMN id_beneficiario int(11) NOT NULL auto_increment COMMENT 'Campo id_beneficiario de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN nacionalidad enum('V','E') NULL DEFAULT 'V' COMMENT 'Campo nacionalidad de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN cedula int(11) NOT NULL COMMENT 'Campo cedula de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN nombre_beneficiario varchar(150) NOT NULL COMMENT 'Campo nombre_beneficiario de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN telefono varchar(20) NULL DEFAULT NULL COMMENT 'Campo telefono de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN id_comunidad int(11) NOT NULL COMMENT 'Campo id_comunidad de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN comunidad varchar(100) NULL DEFAULT NULL COMMENT 'Campo comunidad de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN hora_registro_12h char(11) NULL DEFAULT NULL COMMENT 'Campo hora_registro_12h de la tabla beneficiarios.';
ALTER TABLE beneficiarios MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla beneficiarios.';
ALTER TABLE bitacora MODIFY COLUMN id_bitacora int(11) NOT NULL auto_increment COMMENT 'Campo id_bitacora de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN id_usuario int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN tabla_afectada varchar(64) NULL DEFAULT NULL COMMENT 'Campo tabla_afectada de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN accion varchar(20) NOT NULL DEFAULT 'LEGACY' COMMENT 'Campo accion de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN id_registro varchar(64) NULL DEFAULT NULL COMMENT 'Campo id_registro de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN detalle text NULL COMMENT 'Campo detalle de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN datos_antes longtext NULL COMMENT 'Campo datos_antes de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN datos_despues longtext NULL COMMENT 'Campo datos_despues de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN usuario_bd varchar(100) NULL DEFAULT NULL COMMENT 'Campo usuario_bd de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN moment timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo moment de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN fecha_evento datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_evento de la tabla bitacora.';
ALTER TABLE bitacora MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla bitacora.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN id_chofer_ambulancia int(11) NOT NULL auto_increment COMMENT 'Campo id_chofer_ambulancia de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN id_empleado int(11) NOT NULL COMMENT 'Campo id_empleado de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN numero_licencia varchar(60) NULL DEFAULT NULL COMMENT 'Campo numero_licencia de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN categoria_licencia varchar(40) NULL DEFAULT NULL COMMENT 'Campo categoria_licencia de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN vencimiento_licencia date NULL DEFAULT NULL COMMENT 'Campo vencimiento_licencia de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN contacto_emergencia varchar(120) NULL DEFAULT NULL COMMENT 'Campo contacto_emergencia de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN telefono_contacto_emergencia varchar(30) NULL DEFAULT NULL COMMENT 'Campo telefono_contacto_emergencia de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN observaciones text NULL COMMENT 'Campo observaciones de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla choferes_ambulancia.';
ALTER TABLE choferes_ambulancia MODIFY COLUMN fecha_actualizacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo fecha_actualizacion de la tabla choferes_ambulancia.';
ALTER TABLE comunidades MODIFY COLUMN id_comunidad int(11) NOT NULL auto_increment COMMENT 'Campo id_comunidad de la tabla comunidades.';
ALTER TABLE comunidades MODIFY COLUMN nombre_comunidad varchar(120) NOT NULL COMMENT 'Campo nombre_comunidad de la tabla comunidades.';
ALTER TABLE comunidades MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla comunidades.';
ALTER TABLE comunidades MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla comunidades.';
ALTER TABLE comunidades MODIFY COLUMN hora_registro_12h char(11) NOT NULL DEFAULT '' COMMENT 'Campo hora_registro_12h de la tabla comunidades.';
ALTER TABLE configuracion_smtp MODIFY COLUMN id_configuracion_smtp int(11) NOT NULL auto_increment COMMENT 'Campo id_configuracion_smtp de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN host varchar(150) NOT NULL DEFAULT 'smtp.gmail.com' COMMENT 'Campo host de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN puerto int(11) NOT NULL DEFAULT 587 COMMENT 'Campo puerto de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN usuario varchar(150) NOT NULL COMMENT 'Campo usuario de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN clave varchar(255) NOT NULL COMMENT 'Campo clave de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN correo_remitente varchar(150) NOT NULL COMMENT 'Campo correo_remitente de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN nombre_remitente varchar(150) NULL DEFAULT NULL COMMENT 'Campo nombre_remitente de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN usar_tls tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo usar_tls de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN id_usuario_actualiza int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario_actualiza de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla configuracion_smtp.';
ALTER TABLE configuracion_smtp MODIFY COLUMN fecha_actualizacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo fecha_actualizacion de la tabla configuracion_smtp.';
ALTER TABLE dependencias MODIFY COLUMN id_dependencia int(11) NOT NULL auto_increment COMMENT 'Campo id_dependencia de la tabla dependencias.';
ALTER TABLE dependencias MODIFY COLUMN nombre_dependencia varchar(100) NOT NULL COMMENT 'Campo nombre_dependencia de la tabla dependencias.';
ALTER TABLE dependencias MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla dependencias.';
ALTER TABLE despachos_unidades MODIFY COLUMN id_despacho_unidad int(11) NOT NULL auto_increment COMMENT 'Campo id_despacho_unidad de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN id_seguridad int(11) NOT NULL COMMENT 'Campo id_seguridad de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN id_unidad int(11) NOT NULL COMMENT 'Campo id_unidad de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN id_chofer_ambulancia int(11) NOT NULL COMMENT 'Campo id_chofer_ambulancia de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN id_usuario_asigna int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario_asigna de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN modo_asignacion enum('AUTO','MANUAL') NOT NULL DEFAULT 'AUTO' COMMENT 'Campo modo_asignacion de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN estado_despacho enum('ACTIVO','CERRADO','CANCELADO') NOT NULL DEFAULT 'ACTIVO' COMMENT 'Campo estado_despacho de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN fecha_asignacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_asignacion de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN fecha_cierre datetime NULL DEFAULT NULL COMMENT 'Campo fecha_cierre de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN ubicacion_salida varchar(190) NULL DEFAULT NULL COMMENT 'Campo ubicacion_salida de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN ubicacion_evento varchar(190) NULL DEFAULT NULL COMMENT 'Campo ubicacion_evento de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN ubicacion_cierre varchar(190) NULL DEFAULT NULL COMMENT 'Campo ubicacion_cierre de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN observaciones text NULL COMMENT 'Campo observaciones de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla despachos_unidades.';
ALTER TABLE despachos_unidades MODIFY COLUMN fecha_actualizacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo fecha_actualizacion de la tabla despachos_unidades.';
ALTER TABLE empleados MODIFY COLUMN id_empleado int(11) NOT NULL auto_increment COMMENT 'Campo id_empleado de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN cedula int(11) NOT NULL COMMENT 'Campo cedula de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN nombre varchar(100) NOT NULL COMMENT 'Campo nombre de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN apellido varchar(100) NOT NULL COMMENT 'Campo apellido de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN id_dependencia int(11) NOT NULL COMMENT 'Campo id_dependencia de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN telefono varchar(20) NULL DEFAULT NULL COMMENT 'Campo telefono de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN correo varchar(150) NULL DEFAULT NULL COMMENT 'Campo correo de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN direccion varchar(255) NULL DEFAULT NULL COMMENT 'Campo direccion de la tabla empleados.';
ALTER TABLE empleados MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla empleados.';
ALTER TABLE estados_solicitudes MODIFY COLUMN id_estado_solicitud int(11) NOT NULL auto_increment COMMENT 'Campo id_estado_solicitud de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN codigo_estado varchar(40) NOT NULL COMMENT 'Campo codigo_estado de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN nombre_estado varchar(80) NOT NULL COMMENT 'Campo nombre_estado de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN descripcion varchar(190) NULL DEFAULT NULL COMMENT 'Campo descripcion de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN clase_badge varchar(30) NOT NULL DEFAULT 'draft' COMMENT 'Campo clase_badge de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN es_atendida tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Campo es_atendida de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN orden_visual tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Campo orden_visual de la tabla estados_solicitudes.';
ALTER TABLE estados_solicitudes MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla estados_solicitudes.';
ALTER TABLE permisos MODIFY COLUMN id_permiso int(11) NOT NULL auto_increment COMMENT 'Campo id_permiso de la tabla permisos.';
ALTER TABLE permisos MODIFY COLUMN nombre_permiso varchar(100) NOT NULL COMMENT 'Campo nombre_permiso de la tabla permisos.';
ALTER TABLE permisos MODIFY COLUMN descripcion varchar(255) NULL DEFAULT NULL COMMENT 'Campo descripcion de la tabla permisos.';
ALTER TABLE permisos MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla permisos.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN id_reporte_solicitud int(11) NOT NULL auto_increment COMMENT 'Campo id_reporte_solicitud de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN id_seguridad int(11) NOT NULL COMMENT 'Campo id_seguridad de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN id_despacho_unidad int(11) NULL DEFAULT NULL COMMENT 'Campo id_despacho_unidad de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN tipo_reporte enum('REGISTRO','CIERRE') NOT NULL DEFAULT 'REGISTRO' COMMENT 'Campo tipo_reporte de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN nombre_archivo varchar(180) NOT NULL COMMENT 'Campo nombre_archivo de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN ruta_archivo varchar(255) NOT NULL COMMENT 'Campo ruta_archivo de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN estado_envio enum('NO_APLICA','PENDIENTE','ENVIADO','ERROR') NOT NULL DEFAULT 'NO_APLICA' COMMENT 'Campo estado_envio de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN correo_destino varchar(150) NULL DEFAULT NULL COMMENT 'Campo correo_destino de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN fecha_envio datetime NULL DEFAULT NULL COMMENT 'Campo fecha_envio de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN detalle_envio text NULL COMMENT 'Campo detalle_envio de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN id_usuario_genera int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario_genera de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN fecha_generacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_generacion de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_solicitudes_ambulancia MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla reportes_solicitudes_ambulancia.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_reporte int(11) NOT NULL auto_increment COMMENT 'Campo id_reporte de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_ayuda int(11) NULL DEFAULT NULL COMMENT 'Campo id_ayuda de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_seguridad int(11) NULL DEFAULT NULL COMMENT 'Campo id_seguridad de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_despacho_unidad int(11) NULL DEFAULT NULL COMMENT 'Campo id_despacho_unidad de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_usuario_operador int(11) NOT NULL COMMENT 'Campo id_usuario_operador de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_empleado_chofer int(11) NOT NULL COMMENT 'Campo id_empleado_chofer de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN id_unidad int(11) NOT NULL COMMENT 'Campo id_unidad de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN ticket_interno varchar(20) NOT NULL COMMENT 'Campo ticket_interno de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN fecha_hora datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_hora de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN diagnostico_paciente text NULL COMMENT 'Campo diagnostico_paciente de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN foto_evidencia varchar(255) NULL DEFAULT NULL COMMENT 'Campo foto_evidencia de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN km_salida int(11) NULL DEFAULT NULL COMMENT 'Campo km_salida de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN km_llegada int(11) NULL DEFAULT NULL COMMENT 'Campo km_llegada de la tabla reportes_traslado.';
ALTER TABLE reportes_traslado MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla reportes_traslado.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN id_seguimiento_solicitud int(11) NOT NULL auto_increment COMMENT 'Campo id_seguimiento_solicitud de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN modulo enum('AYUDA_SOCIAL','SEGURIDAD','SERVICIOS_PUBLICOS') NOT NULL COMMENT 'Campo modulo de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN id_referencia int(11) NOT NULL COMMENT 'Campo id_referencia de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN id_estado_solicitud int(11) NOT NULL COMMENT 'Campo id_estado_solicitud de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN id_usuario int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN fecha_gestion datetime NOT NULL COMMENT 'Campo fecha_gestion de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN observacion text NULL COMMENT 'Campo observacion de la tabla seguimientos_solicitudes.';
ALTER TABLE seguimientos_solicitudes MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla seguimientos_solicitudes.';
ALTER TABLE seguridad MODIFY COLUMN id_seguridad int(11) NOT NULL auto_increment COMMENT 'Campo id_seguridad de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN ticket_interno varchar(20) NULL DEFAULT NULL COMMENT 'Campo ticket_interno de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN id_beneficiario int(11) NOT NULL COMMENT 'Campo id_beneficiario de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN id_usuario int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN id_tipo_seguridad int(11) NULL DEFAULT NULL COMMENT 'Campo id_tipo_seguridad de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN id_solicitud_seguridad int(11) NULL DEFAULT NULL COMMENT 'Campo id_solicitud_seguridad de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN id_estado_solicitud int(11) NULL DEFAULT NULL COMMENT 'Campo id_estado_solicitud de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN tipo_seguridad varchar(100) NULL DEFAULT NULL COMMENT 'Campo tipo_seguridad de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN tipo_solicitud varchar(100) NULL DEFAULT NULL COMMENT 'Campo tipo_solicitud de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN fecha_seguridad datetime NULL DEFAULT NULL COMMENT 'Campo fecha_seguridad de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN descripcion text NULL COMMENT 'Campo descripcion de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN estado_atencion enum('REGISTRADO','PENDIENTE_UNIDAD','DESPACHADO','FINALIZADO','ANULADO') NOT NULL DEFAULT 'REGISTRADO' COMMENT 'Campo estado_atencion de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN ubicacion_evento varchar(190) NULL DEFAULT NULL COMMENT 'Campo ubicacion_evento de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN referencia_evento varchar(190) NULL DEFAULT NULL COMMENT 'Campo referencia_evento de la tabla seguridad.';
ALTER TABLE seguridad MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla seguridad.';
ALTER TABLE servicios_publicos MODIFY COLUMN id_servicio int(11) NOT NULL auto_increment COMMENT 'Campo id_servicio de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN ticket_interno varchar(20) NULL DEFAULT NULL COMMENT 'Campo ticket_interno de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN id_beneficiario int(11) NOT NULL COMMENT 'Campo id_beneficiario de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN id_usuario int(11) NULL DEFAULT NULL COMMENT 'Campo id_usuario de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN id_tipo_servicio_publico int(11) NULL DEFAULT NULL COMMENT 'Campo id_tipo_servicio_publico de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN id_solicitud_servicio_publico int(11) NULL DEFAULT NULL COMMENT 'Campo id_solicitud_servicio_publico de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN id_estado_solicitud int(11) NULL DEFAULT NULL COMMENT 'Campo id_estado_solicitud de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN tipo_servicio varchar(100) NULL DEFAULT NULL COMMENT 'Campo tipo_servicio de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN solicitud_servicio varchar(100) NULL DEFAULT NULL COMMENT 'Campo solicitud_servicio de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN fecha_servicio date NULL DEFAULT NULL COMMENT 'Campo fecha_servicio de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN descripcion text NULL COMMENT 'Campo descripcion de la tabla servicios_publicos.';
ALTER TABLE servicios_publicos MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla servicios_publicos.';
ALTER TABLE solicitudes_generales MODIFY COLUMN id_solicitud_general int(11) NOT NULL auto_increment COMMENT 'Campo id_solicitud_general de la tabla solicitudes_generales.';
ALTER TABLE solicitudes_generales MODIFY COLUMN codigo_solicitud varchar(20) NOT NULL COMMENT 'Campo codigo_solicitud de la tabla solicitudes_generales.';
ALTER TABLE solicitudes_generales MODIFY COLUMN nombre_solicitud varchar(120) NOT NULL COMMENT 'Campo nombre_solicitud de la tabla solicitudes_generales.';
ALTER TABLE solicitudes_generales MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla solicitudes_generales.';
ALTER TABLE solicitudes_generales MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla solicitudes_generales.';
ALTER TABLE tipos_ayuda_social MODIFY COLUMN id_tipo_ayuda_social int(11) NOT NULL auto_increment COMMENT 'Campo id_tipo_ayuda_social de la tabla tipos_ayuda_social.';
ALTER TABLE tipos_ayuda_social MODIFY COLUMN nombre_tipo_ayuda varchar(120) NOT NULL COMMENT 'Campo nombre_tipo_ayuda de la tabla tipos_ayuda_social.';
ALTER TABLE tipos_ayuda_social MODIFY COLUMN requiere_ambulancia tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Campo requiere_ambulancia de la tabla tipos_ayuda_social.';
ALTER TABLE tipos_ayuda_social MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla tipos_ayuda_social.';
ALTER TABLE tipos_ayuda_social MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla tipos_ayuda_social.';
ALTER TABLE tipos_seguridad_emergencia MODIFY COLUMN id_tipo_seguridad int(11) NOT NULL auto_increment COMMENT 'Campo id_tipo_seguridad de la tabla tipos_seguridad_emergencia.';
ALTER TABLE tipos_seguridad_emergencia MODIFY COLUMN nombre_tipo varchar(120) NOT NULL COMMENT 'Campo nombre_tipo de la tabla tipos_seguridad_emergencia.';
ALTER TABLE tipos_seguridad_emergencia MODIFY COLUMN requiere_ambulancia tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Campo requiere_ambulancia de la tabla tipos_seguridad_emergencia.';
ALTER TABLE tipos_seguridad_emergencia MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla tipos_seguridad_emergencia.';
ALTER TABLE tipos_seguridad_emergencia MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla tipos_seguridad_emergencia.';
ALTER TABLE tipos_servicios_publicos MODIFY COLUMN id_tipo_servicio_publico int(11) NOT NULL auto_increment COMMENT 'Campo id_tipo_servicio_publico de la tabla tipos_servicios_publicos.';
ALTER TABLE tipos_servicios_publicos MODIFY COLUMN codigo_tipo_servicio_publico varchar(20) NOT NULL COMMENT 'Campo codigo_tipo_servicio_publico de la tabla tipos_servicios_publicos.';
ALTER TABLE tipos_servicios_publicos MODIFY COLUMN nombre_tipo_servicio varchar(120) NOT NULL COMMENT 'Campo nombre_tipo_servicio de la tabla tipos_servicios_publicos.';
ALTER TABLE tipos_servicios_publicos MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla tipos_servicios_publicos.';
ALTER TABLE tipos_servicios_publicos MODIFY COLUMN fecha_registro datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_registro de la tabla tipos_servicios_publicos.';
ALTER TABLE unidades MODIFY COLUMN id_unidad int(11) NOT NULL auto_increment COMMENT 'Campo id_unidad de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN codigo_unidad varchar(20) NOT NULL COMMENT 'Campo codigo_unidad de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN descripcion varchar(100) NULL DEFAULT NULL COMMENT 'Campo descripcion de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN placa varchar(15) NOT NULL COMMENT 'Campo placa de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN estado_operativo enum('DISPONIBLE','EN_SERVICIO','FUERA_SERVICIO') NOT NULL DEFAULT 'DISPONIBLE' COMMENT 'Campo estado_operativo de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN ubicacion_actual varchar(190) NULL DEFAULT NULL COMMENT 'Campo ubicacion_actual de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN referencia_actual varchar(190) NULL DEFAULT NULL COMMENT 'Campo referencia_actual de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN prioridad_despacho int(11) NOT NULL DEFAULT 100 COMMENT 'Campo prioridad_despacho de la tabla unidades.';
ALTER TABLE unidades MODIFY COLUMN fecha_actualizacion_operativa datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Campo fecha_actualizacion_operativa de la tabla unidades.';
ALTER TABLE usuarios MODIFY COLUMN id_empleado int(11) NOT NULL COMMENT 'Campo id_empleado de la tabla usuarios.';
ALTER TABLE usuarios MODIFY COLUMN usuario varchar(50) NOT NULL COMMENT 'Campo usuario de la tabla usuarios.';
ALTER TABLE usuarios MODIFY COLUMN password varchar(64) NOT NULL COMMENT 'Campo password de la tabla usuarios.';
ALTER TABLE usuarios MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla usuarios.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN id_usuario int(11) NOT NULL COMMENT 'Campo id_usuario de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN intentos_fallidos int(11) NOT NULL DEFAULT 0 COMMENT 'Campo intentos_fallidos de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN bloqueado tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Campo bloqueado de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN fecha_bloqueo datetime NULL DEFAULT NULL COMMENT 'Campo fecha_bloqueo de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN password_temporal tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Campo password_temporal de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN fecha_password_temporal datetime NULL DEFAULT NULL COMMENT 'Campo fecha_password_temporal de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuarios_seguridad_acceso MODIFY COLUMN fecha_actualizacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP on update current_timestamp() COMMENT 'Campo fecha_actualizacion de la tabla usuarios_seguridad_acceso.';
ALTER TABLE usuario_permisos MODIFY COLUMN id_usuario_permiso int(11) NOT NULL auto_increment COMMENT 'Campo id_usuario_permiso de la tabla usuario_permisos.';
ALTER TABLE usuario_permisos MODIFY COLUMN id_usuario int(11) NOT NULL COMMENT 'Campo id_usuario de la tabla usuario_permisos.';
ALTER TABLE usuario_permisos MODIFY COLUMN id_permiso int(11) NOT NULL COMMENT 'Campo id_permiso de la tabla usuario_permisos.';
ALTER TABLE usuario_permisos MODIFY COLUMN estado tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Campo estado de la tabla usuario_permisos.';
